language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
bundler_args: --without development
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cp config/database.yml.travis config/database.yml"
  - "mysql -e 'create database aircasting_test;'"
  - "RAILS_ENV=test bundle exec rake db:migrate"
script:
  - "bundle exec rspec spec/spec_helper.rb spec && DISPLAY=:99.0 RAILS_ENV=test bundle exec rake jasmine:headless"
